services:
  - type: web
    name: whisper-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 5000
    pythonVersion: "3.11" 