services:
  - type: web
    name: whisper-backend
    env: node
    buildCommand: |
      pip install -r requirements.txt
      npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000 