services:
  - type: web
    name: whisper-backend
    env: python
    buildCommand: |
      echo "Installing system dependencies..."
      apt-get update
      apt-get install -y ffmpeg
      ffmpeg -version
      echo "Installing Python dependencies..."
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 300 --log-level debug
    envVars:
      - key: PORT
        value: 5000
    pythonVersion: "3.11"
    plan: standard
    healthCheckPath: /test
    autoDeploy: true 